### ISSUE TITLE
Forbidden to access files in styles/all/templates

### ISSUE THREAD

**Issue by Rai-Rai** [david63/david63-privacypolicy#6]
Hi,
just downloaded the newest version of your extension. It mostly works fine.
But I'm getting 403 FORBIDDEN errors for some files for the cookie policy.

So if a user clicks on Register or Login, he only gets the message
"COOKIE ACCEPTANCE REQUIRED
You must accept the Cookie Policy of FanFictionDownloader.net before you can either register on this site or, if you are already registered, before you can login to the site."
But no way to accept them. 

Request URL: MY_DOMAINt/ext/david63/privacypolicy/styles/all/template/cookie_page.js?assets_version=11
Request Method: GET
Status Code: 403 Forbidden

also for:
/ext/david63/privacypolicy/styles/all/template/remove_url.js?assets_version=11
/ext/david63/privacypolicy/styles/all/template/cookie_fn.js?assets_version=11

**Comment by david63** [comment]
There is no forum at that site so I cannot check what is happening.

403 errors are server errors, not extension errors.

In future please post errors/problem in the support topic at phpbb.com
