### ISSUE TITLE
The IP lookup has failed message in error log

### ISSUE THREAD

**Issue by Naguissa** [david63/david63-privacypolicy#7]
Hello,

It seems freegeoip.net is changed and has deprecated the URL this extension is using to get IP's country.

Given so, the error message is constantly getting logged, son any lookup fails.

I've tracked that to event/listener.php file, on 	function check_ip($user_ip).

As a quick fix I've added at the beginning a "return true;" statement, making popup to always appear.

I suggest changing to another service and/or using geoIP if available to do so.

Cheers!

**Comment by david63** [comment]
I don't know which version you are using but that check has not been in for many months.

I would suggest that you update to the latest released version.
